# Generated by Django 3.0.4 on 2020-04-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0002_element_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(upload_to='images/')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listelement.Element')),
            ],
        ),
    ]
