# Generated by Django 3.0.4 on 2020-09-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0005_auto_20200507_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='url_clean',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
