# Generated by Django 3.0.4 on 2020-03-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200322_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='document',
            field=models.FileField(default='', null=True, upload_to='uploads/contact'),
        ),
    ]
