# Generated by Django 3.0.4 on 2020-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20200322_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='document',
            field=models.FileField(default=None, null=True, upload_to='uploads/contact'),
        ),
    ]
