# Generated by Django 3.0.4 on 2020-03-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_contact_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comment.TypeContact'),
        ),
    ]
